# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.IntegerField()),
                ('symbol', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('portfolio_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.TimeField()),
                ('stock_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=50)),
                ('hash', models.CharField(max_length=50)),
                ('cash', models.FloatField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
